// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package domain

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Changes    []byte             `json:"changes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type BusinessLine struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Code      pgtype.Text        `json:"code"`
	Name      string             `json:"name"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type BusinessUnit struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Code      pgtype.Text        `json:"code"`
	Name      string             `json:"name"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Department struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	ParentDepartmentID pgtype.UUID        `json:"parent_department_id"`
	Code               pgtype.Text        `json:"code"`
	Name               string             `json:"name"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Employee struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	EmployeeNo     string             `json:"employee_no"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	DisplayName    pgtype.Text        `json:"display_name"`
	WorkEmail      pgtype.Text        `json:"work_email"`
	Status         string             `json:"status"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	BusinessUnitID pgtype.UUID        `json:"business_unit_id"`
	DepartmentID   pgtype.UUID        `json:"department_id"`
	JobTitleID     pgtype.UUID        `json:"job_title_id"`
	ManagerID      pgtype.UUID        `json:"manager_id"`
}

type EmployeeAssignment struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	EmployeeID        pgtype.UUID        `json:"employee_id"`
	BusinessUnitID    pgtype.UUID        `json:"business_unit_id"`
	DepartmentID      pgtype.UUID        `json:"department_id"`
	BusinessLineID    pgtype.UUID        `json:"business_line_id"`
	JobTitleID        pgtype.UUID        `json:"job_title_id"`
	ManagerEmployeeID pgtype.UUID        `json:"manager_employee_id"`
	EffectiveFrom     pgtype.Date        `json:"effective_from"`
	EffectiveTo       pgtype.Date        `json:"effective_to"`
	IsPrimary         bool               `json:"is_primary"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type JobTitle struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Code      pgtype.Text        `json:"code"`
	Name      string             `json:"name"`
	Grade     pgtype.Text        `json:"grade"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RbacRole struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	Email        string             `json:"email"`
	DisplayName  pgtype.Text        `json:"display_name"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	IsActive     bool               `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserRbacRole struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	RoleID          pgtype.UUID        `json:"role_id"`
	BusinessUnitID  pgtype.UUID        `json:"business_unit_id"`
	DepartmentID    pgtype.UUID        `json:"department_id"`
	GrantedAt       pgtype.Timestamptz `json:"granted_at"`
	GrantedByUserID pgtype.UUID        `json:"granted_by_user_id"`
}
