// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package domain

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountBusinessUnits(ctx context.Context, arg CountBusinessUnitsParams) (int64, error)
	CountDepartments(ctx context.Context, arg CountDepartmentsParams) (int64, error)
	CountEmployees(ctx context.Context, arg CountEmployeesParams) (int64, error)
	CountJobTitles(ctx context.Context, arg CountJobTitlesParams) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateBusinessUnit(ctx context.Context, arg CreateBusinessUnitParams) (BusinessUnit, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	CreateJobTitle(ctx context.Context, arg CreateJobTitleParams) (JobTitle, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (RbacRole, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetBusinessUnit(ctx context.Context, arg GetBusinessUnitParams) (BusinessUnit, error)
	GetDepartment(ctx context.Context, arg GetDepartmentParams) (Department, error)
	GetEmployee(ctx context.Context, arg GetEmployeeParams) (Employee, error)
	GetEmployeeHierarchy(ctx context.Context, arg GetEmployeeHierarchyParams) ([]GetEmployeeHierarchyRow, error)
	GetEmployeeWithDetails(ctx context.Context, arg GetEmployeeWithDetailsParams) (GetEmployeeWithDetailsRow, error)
	GetJobTitle(ctx context.Context, arg GetJobTitleParams) (JobTitle, error)
	GetRole(ctx context.Context, arg GetRoleParams) (RbacRole, error)
	GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error)
	GetUser(ctx context.Context, arg GetUserParams) (User, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserForLogin(ctx context.Context, email string) (User, error)
	GetUserRoles(ctx context.Context, arg GetUserRolesParams) ([]string, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListBusinessUnits(ctx context.Context, arg ListBusinessUnitsParams) ([]BusinessUnit, error)
	ListDepartments(ctx context.Context, arg ListDepartmentsParams) ([]Department, error)
	ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Employee, error)
	ListEmployeesWithDetails(ctx context.Context, arg ListEmployeesWithDetailsParams) ([]ListEmployeesWithDetailsRow, error)
	ListJobTitles(ctx context.Context, arg ListJobTitlesParams) ([]JobTitle, error)
	ListRoles(ctx context.Context, tenantID pgtype.UUID) ([]RbacRole, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RevokeUserRole(ctx context.Context, arg RevokeUserRoleParams) error
}

var _ Querier = (*Queries)(nil)
